[package]
name = "cloud-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trash = "4.1.0"
[dependencies.regex]
version = "1.3"
default-features = false
features = ["std", "unicode-perl"]
